### ISSUE TITLE
Epic: /api/groups

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/ST2020#192]
Create a new file `groups.py` for these endpoints

- [x] **GET /api/groups** (list_groups)
  Requires authentication. Returns a list of all group codes and display names, e.g. `[{ "group_code": "ACH", "group_name": "Alberta" }]`

- [x] **GET /api/groups/:group_code** (get_group)
  Returns `{ "group_code": "", "group_name": "",  "users": [] }` where each field is filled out accordingly. The `users` array should be an array of usernames of the users in the group and can be obtained from the `users` relation on the Group model as a backref from User. Admins can use this endpoint for all groups. Regulars can only use this for groups they belong to or they get a 403 Forbidden.

- [x] **POST /api/groups** (create_group)
  Admin-only. Creates a new group with the specified codename, display name, and users (same format as the get_group endpoint return result, but the users array is optional). This also creates a corresponding MinIO group (via madmin.MinioAdmin) and bucket (via MinioClient). The group should have an access policy that gives it complete access to its bucket. The corresponding MinIO users should be added to this group. Fail with 422 if the bucket already exists (do not create a group in the database in this case) or the code/name are already in use. Fail with 404 if a user to be added doesn't exist. The return result should be of the same form as `get_group` and the URL to the created resource should be in the Location header.

- [x] **PATCH /api/groups** (update_groups)
  Admin-only. Updates requested fields accordingly. The group code cannot be changed but the display name can be. Users should be added and removed accordingly and the error codes are the same as create_group.

- [x] **DELETE /api/groups/:group_code** (delete_group)
  Admin-only. Deletes the group and the MinIO group if they are empty but retains the MinIO bucket, otherwise fail with 422.
