### ISSUE TITLE
Fix all endpoints that return user PKs to return usernames

### ISSUE THREAD

**Issue by kevinlul** [ccmbioinfo/ST2020#209]
e.g. https://github.com/ccmbioinfo/ST2020/blob/master/flask/app/analyses.py#L68

Update unit tests accordingly

**Comment by delvinso** [comment]
- [x] rename user foreign keys and add user relationship to each table (#244)
- [x] fix unit tests and in turn, fix all endpoints previously referencing created_by and updated_by  (#244)
     - [x ] datasets, families, manage, models, participants, routes
- [x] fix current endpoints returning usernames (analyses and datasets)  (#244)
- [ ] fix endpoints returning pk to return usernames
